services:
  - type: web
    name: sadad-control-server
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PORT
        value: 10000
      - key: SHEET_ID
        sync: false
      - key: SERVICE_ACCOUNT_JSON
        sync: false
      - key: REDIS_URL
        sync: false
